Repository brayan9304/spartacus-training, pull requests merged in 2021-11, with the labels that each got.

#31 Add to cart functionality from the saved-list-detail page for each pr…
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/assets/translations/translations.ts
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.html
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.scss
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.ts
  js-storefront/taloscommercestore/src/assets/i18n-assets/en/tcSavedList.json
Labels: FE-intership

#33 Bug fix: Adding the same product to different new lists through the m…
  js-storefront/taloscommercestore/src/app/spartacus/shared/cms-components/content/tc-saved-list-modal/tc-saved-list-modal.component.ts
Labels: bug, FE-intership

#34 Clean code and add spinner on detail page
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.html
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.scss
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.ts
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.module.ts
Labels: FE-intership

#35 Changed the saved-list-list page action icons
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-list/tc-saved-list-list.component.html
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-list/tc-saved-list-list.component.scss
  js-storefront/taloscommercestore/src/assets/i18n-assets/en/tcSavedList.json
Labels: bug, FE-intership

#36 Added info and error messages to ease user navigation
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-list/tc-saved-list-list.component.html
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-list/tc-saved-list-list.component.scss
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-list/tc-saved-list-list.component.ts
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-list/tc-saved-list-list.module.ts
  js-storefront/taloscommercestore/src/assets/i18n-assets/en/tcSavedList.json
Labels: bug, FE-intership

#37 Feature/saved list detail improvements
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.html
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.scss
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.ts
  js-storefront/taloscommercestore/src/assets/i18n-assets/en/tcSavedList.json
Labels: bug, FE-intership

#38 Minor bug fixes regarding the last improvement
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.html
  js-storefront/taloscommercestore/src/app/spartacus/shared/cms-components/content/tc-saved-list-modal/tc-saved-list-modal.component.ts
Labels: bug, FE-intership

#32 CreatedList returning new Id
  core-customize/tccommercewebservices/web/src/com/taloscommerce/webservices/v2/controller/CustomProductListController.java
Labels: bug, BE-intership

#40 Fixed spacing of saved-list-list buttons when there is no description…
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-list/tc-saved-list-list.component.scss
  js-storefront/taloscommercestore/src/assets/i18n-assets/en/tcSavedList.json
Labels: bug, FE-intership

#39 Fix router links
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.html
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.scss
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.ts
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.module.ts
Labels: bug, FE-intership

#41 Saved-list-list minor bug fixes
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-list/tc-saved-list-list.component.html
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-list/tc-saved-list-list.component.scss
  js-storefront/taloscommercestore/src/assets/i18n-assets/en/tcSavedList.json
Labels: bug, FE-intership

#42 Fixing the problem with images not loading
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.html
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.scss
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.ts
Labels: bug, FE-intership

#43 Feature/saved list input search
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.html
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.ts
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.module.ts
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-list/tc-saved-list-list.component.html
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-list/tc-saved-list-list.component.scss
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-list/tc-saved-list-list.component.ts
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-list/tc-saved-list-list.module.ts
  js-storefront/taloscommercestore/src/app/spartacus/shared/cms-components/content/index.ts
  js-storefront/taloscommercestore/src/app/spartacus/shared/cms-components/content/tc-saved-list-modal/tc-saved-list-modal.module.ts
  js-storefront/taloscommercestore/src/app/spartacus/shared/cms-components/content/tc-saved-list-search-bar/index.ts
  js-storefront/taloscommercestore/src/app/spartacus/shared/cms-components/content/tc-saved-list-search-bar/tc-saved-list-search-bar.component.html
  js-storefront/taloscommercestore/src/app/spartacus/shared/cms-components/content/tc-saved-list-search-bar/tc-saved-list-search-bar.component.scss
  js-storefront/taloscommercestore/src/app/spartacus/shared/cms-components/content/tc-saved-list-search-bar/tc-saved-list-search-bar.component.spec.ts
  js-storefront/taloscommercestore/src/app/spartacus/shared/cms-components/content/tc-saved-list-search-bar/tc-saved-list-search-bar.component.ts
  js-storefront/taloscommercestore/src/app/spartacus/shared/cms-components/content/tc-saved-list-search-bar/tc-saved-list-search-bar.module.ts
  js-storefront/taloscommercestore/src/app/spartacus/shared/index.ts
  js-storefront/taloscommercestore/src/app/spartacus/shared/pipes/filter.pipe.spec.ts
  js-storefront/taloscommercestore/src/app/spartacus/shared/pipes/filter.pipe.ts
  js-storefront/taloscommercestore/src/app/spartacus/shared/pipes/index.ts
  js-storefront/taloscommercestore/src/app/spartacus/shared/pipes/pipes.module.ts
Labels: FE-intership

#44 The search filter's placeholder can be changed my who implements the …
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/assets/translations/translations.ts
  js-storefront/taloscommercestore/src/app/spartacus/features/tc-saved-list/components/tc-saved-list-detail/tc-saved-list-detail.component.ts
  js-storefront/taloscommercestore/src/app/spartacus/shared/cms-components/content/tc-saved-list-search-bar/tc-saved-list-search-bar.component.html
  js-storefront/taloscommercestore/src/app/spartacus/shared/cms-components/content/tc-saved-list-search-bar/tc-saved-list-search-bar.component.ts
  js-storefront/taloscommercestore/src/app/spartacus/shared/cms-components/content/tc-saved-list-search-bar/tc-saved-list-search-bar.module.ts
  js-storefront/taloscommercestore/src/assets/i18n-assets/en/tcSavedList.json
Labels: FE-intership
